# Retail Sales Analysis

## Project Overview

This project analyzes retail sales performance across different regions, customer segments, and product categories.

The goal is to identify sales trends, understand customer behavior, and provide business recommendations based on data insights.

## Tools Used

- Python (Pandas)
- MySQL
- Power BI
- GitHub

## Project Workflow

1. Data Inspection
2. Data Cleaning
3. Feature Engineering
4. Data Export
5. SQL Analysis
6. Dashboard Development
7. Business Insights

## 1. Import Libraries

In this section, we import the required Python libraries for data analysis and data cleaning.

In [25]:
# Load Dataset
# Check missing values
# Check duplicates
# Convert date type
# Load the original sales dataset, and perform an initial inspection.
import pandas as pd
import numpy as np

## 2. Load Dataset

Load the retail sales dataset and perform an initial inspection.

In [26]:
df = pd.read_csv("./data/train.csv")
#display the first 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

## 3. Dataset Overview

Understand the dataset structure, column names, data types, and overall size.

In [28]:
# Display dataset information
df.info()
# Display basic statistics to understand the dataset structure, data types, and summary statistics.
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [29]:
df.shape

(9800, 18)

In [30]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')

## 4. Missing Value Analysis

Check whether the dataset contains missing values and determine appropriate handling strategies.

In [31]:
# Count missing values in each column to identify columns with missing values.
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Observation

The dataset contains a small number of missing values in the Postal Code column.

Since postal code is not critical for this analysis, records with missing postal codes will be removed.

In [32]:
# Remove rows with missing postal codes
df = df.dropna(subset=["Postal Code"])

## 5. Duplicate Analysis

Identify and remove duplicate records to ensure data quality.

In [33]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [34]:
# Count duplicate rows to ensure data quality by removing duplicate records.
df.duplicated().sum()

np.int64(0)

## 6. Date Transformation

Convert date columns into datetime format to support time-based analysis.

In [43]:
# Convert order date to datetime format
# Convert date columns into datetime format for time-series analysis.
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True
)

# Convert ship date to datetime format
df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    dayfirst=True
)

## 7. Feature Engineering

Create additional time-related features for sales trend analysis.

In [44]:
# Extract year from order date
df["Year"] = df["Order Date"].dt.year

# Extract month from order date
df["Month"] = df["Order Date"].dt.month

# Extract quarter from order date
df["Quarter"] = df["Order Date"].dt.quarter

## 8. Exploratory Data Analysis

Perform basic exploratory analysis to understand sales distribution.

In [36]:
# Total Sales
df["Sales"].sum()

np.float64(2252607.4127)

In [37]:
# Sales by Region
df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [39]:
# Sales by Segment
df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

Segment
Consumer       1.146708e+06
Corporate      6.822118e+05
Home Office    4.236874e+05
Name: Sales, dtype: float64

In [38]:
# Top 10 states
df.groupby("State")["Sales"].sum()\
.sort_values(ascending=False)\
.head(10)

State
California      446306.4635
New York        306361.1470
Texas           168572.5322
Washington      135206.8500
Pennsylvania    116276.6500
Florida          88436.5320
Illinois         79236.5170
Michigan         76136.0740
Ohio             75130.3500
Virginia         70636.7200
Name: Sales, dtype: float64

In [40]:
#Top 10 products
df.groupby("Product Name")["Sales"].sum()\
.sort_values(ascending=False)\
.head(10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

## 9. Data Validation

Verify the cleaned dataset before exporting.

In [41]:
# Verify the cleaned dataset
# Validate the dataset after data cleaning and transformation.
df.info()

# Preview cleaned data
df.head()

<class 'pandas.DataFrame'>
Index: 9789 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9789 non-null   int64
 1   Order ID       9789 non-null   str
 2   Order Date     9789 non-null   str
 3   Ship Date      9789 non-null   str
 4   Ship Mode      9789 non-null   str
 5   Customer ID    9789 non-null   str
 6   Customer Name  9789 non-null   str
 7   Segment        9789 non-null   str
 8   Country        9789 non-null   str
 9   City           9789 non-null   str
 10  State          9789 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9789 non-null   str
 13  Product ID     9789 non-null   str
 14  Category       9789 non-null   str
 15  Sub-Category   9789 non-null   str
 16  Product Name   9789 non-null   str
 17  Sales          9789 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.4 MB

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

## 10. Export Cleaned Dataset

Export the cleaned dataset for SQL analysis and Power BI dashboard development.

In [42]:
# Export cleaned dataset
df.to_csv(
    "./data/cleaned_sales.csv",
    index=False,
    encoding="utf-8"
)

# Summary

The dataset was successfully cleaned and transformed for further analysis.

Key data preparation activities included:

- Missing value handling
- Duplicate record validation
- Date transformation
- Feature engineering
- Data quality verification

The cleaned dataset will be used for SQL analysis and Power BI dashboard development in the next phase of the project.